### ISSUE TITLE
"Prerequisites" in readme is inaccurate

### ISSUE THREAD

**Issue by kristofferR** [ReddestDream/OcQuirks#4]
Found a small issue in the readme. The "Prerequisites" section states that FwRuntimeServices.efi needs to be downloaded separately, but it is actually already included in the release.

Thanks for this tool btw, worked fantastic for me! :)

**Comment by ReddestDream** [comment]
Yeah. I included it in there for convenience and ease of testing, but if you build and setup OcQuirks yourself, you need to also get FwRuntimeServices yourself. The release builds are just for convenience since they are known-working. You really should build OcQuirks yourself against the latest OcSupportPkg and build the latest FwRuntimeServices with AppleSupportPkg if you really want to stay up to date. Also if you need to change any of the Quirk values for your own hardware, you need to recompile. Thanks! :)

**Comment by ReddestDream** [comment]
I removed FwRuntimeServices.efi from the release package as I don't want to be supplying it.

**Comment by ReddestDream** [comment]
I tried this, but I discovered that several scripts depend on  FwRuntimeServices.efi being in the zip file at this point. So I have to include it. :/
