### ISSUE TITLE
Stuck at "AMF: Only 55/255 slide values are useable"

### ISSUE THREAD

**Issue by ghost** [ReddestDream/OcQuirks#9]
Hi, I was doing some tests on SMBIOS choices for my Skylake laptop. For a long time, I had been using clover with SMBIOS for MBP14,1 because it will boot only with this choice while opting for MBP13,1 or others will be stuck at boot.

In OC, I am able to boot with SMBIOS 13,1. No problem.

But with SMBIOS 13,1, I am not able to boot with Clover using aptiomemoryfix+FWruntimeservices. 

If there is a way for me to assist, do guide me through the process of gathering debug files.

**Comment by ReddestDream** [comment]
Don't use aptiomemoryfix+FWruntimeservices. OcQuirks requires fwruntimeservices for the same reason OC does (to provide "runtime" fixes). But AptioMemoryFix does not and using fwruntimeservices can actually break AptioMemoryFix.

OcQuirks is a WIP replacement for AptioMemoryFix that uses OC code to make a driver that works on Clover. This driver, OcQuirks.efi, requires fwruntimeservices.efi. If you can already use OC w/o issue, I suggest you do that. I made OcQuirks because AptioMemoryFix is no longer maintained (although I keep a fork compiling) and some people (especially users of VoodooI2C) cannot use OC and need features/behaviors of Clover.

**Comment by ghost** [comment]
What was I thinking still using Aptiomemoryfix! Now, it works! I would like to test this with few more day usage. 

I am a voodooI2C user and also has working OC set up on a thumb drive. There are 2 ways that I know of that is possible. Skip-Count method in OC and INI method for some ACPI tables that allows it. Both of which I am able to get multitouch trackpad running.

I will update again if there are any issues with OCquirks. Cheers!

For now, I will consider it solved and close.

**Comment by ghost** [comment]
Said it too soon. Only works on first boot. i.e when using MBP13,3. Booting with the usual MBP14,1 has no issue.

**Comment by ReddestDream** [comment]
Try disabling/removing things in your BIOS like TPM/SGX/etc to free up more under 4 GB memory and improve boot consistency. I am keeping this issue closed tho as this seems to be outside the scope of issues with OcQuirks itself. Rather, this appears to be a configuration issue. You are welcome to ask questions on the /r/hackintosh reddit or their Discord (where I am active).
